test_ext.lo: /usr/local/src/php-5.3.8/ext/test_ext/test_ext.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/usr/local/src/php-5.3.8/ext/test_ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /usr/local/src/php-5.3.8/ext/test_ext/test_ext.c -o test_ext.lo 
$(phplibdir)/test_ext.la: ./test_ext.la
	$(LIBTOOL) --mode=install cp ./test_ext.la $(phplibdir)

./test_ext.la: $(shared_objects_test_ext) $(TEST_EXT_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_test_ext) $(TEST_EXT_SHARED_LIBADD)

